trigger: 
  branches:
    include:
      - main
  paths:
    exclude:
      - README.md
      - '*.png'
      - azure-pipelines.yml

pool:
  vmImage: 'ubuntu-latest'

variables:
  serviceConnection: $(serviceConnection)
  resourceGroup: $(resourceGroup)
  location: $(location)

stages:
- stage: vaultDeployment
  jobs:
  - job: DeployVaultJob
    steps:
    - task: AzureResourceManagerTemplateDeployment@3
      inputs:
        deploymentScope: 'Resource Group'
        azureResourceManagerConnection: $(serviceConnection)
        subscriptionId: $(subscriptionId)
        action: 'Create Or Update Resource Group'
        resourceGroupName: $(resourceGroup)
        location: $(location)
        templateLocation: 'Linked artifact'
        csmFile: 'main.bicep'
        deploymentMode: 'Incremental' 