trigger:
  branches:
    include:
      - main
  paths:
    exclude:
      - '*.yml'
  

pool:
  vmImage: ubuntu-latest

stages:
- stage: FetchSecret
  displayName: FetchSecret
  jobs:
    - job: FetchSecret
      displayName: FetchingSecret
      steps:
      - task: AzureKeyVault@2
        inputs:
          azureSubscription: 'new-sc-project-17'
          KeyVaultName: '$(kvName)'
          SecretsFilter: 'test1'
          RunAsPreJob: false
      
      - script: |
         echo "Listing secrets"
         echo '$(test1)'
         # env | grep -i "secret" | cut -d= -f1

      - script: |
          echo "The secret was found and has a length of: ${#SECRET_VALUE}"
          env:
              SECRET_VALUE: $(test1)
          displayName: 'Check Secret Metadata'
